### ISSUE TITLE
Add internationalization for landing-page

### ISSUE THREAD

**Issue by use-to** [helpwave/web#56]
On the long run we should be able to serve different languages (english and german).

**Comment by JannikWibker** [comment]
I started working on this but we need texts which are a bit more similar in length as it messes with the layout otherwise.
I'm kind of waiting for #46 to get merged, would be nice if it could get reviewed soon.

here's a quick demo (with a bunch of incomplete things and a "toggle language" button for testing):

https://user-images.githubusercontent.com/16372321/215283858-bca10bfc-f3e3-4080-bd73-c1babdcb92b5.mp4
