### ISSUE TITLE
Assign tasks to user

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#667]
### Describe the feature

- [ ] Re-Enable the assignee options on the task details
- [ ] The available assignees for a task are all available members of an organization. _See [GetMembersByOrganizationRequest](https://proto.helpwave.de/#proto.services.user_svc.v1.GetMembersByOrganizationRequest)_

### Why is this feature needed?

To assigne tasks to a user

**Comment by MaxSchaefer** [comment]
Waiting for https://github.com/helpwave/services/issues/381

**Comment by DasProffi** [comment]
There is no way of obtaining the organization id on this view for now, the implementation of the breadcrumb resolve is blocking this https://github.com/helpwave/services/pull/387 
Another option is to use the organization id returned in the GetWard Request, but this is a open PR right now https://github.com/helpwave/services/pull/374

Until one of them is resolved this issue is blocked

**Comment by DasProffi** [comment]
https://github.com/helpwave/services/pull/374 merged therefore the not ready label will be removed
