### ISSUE TITLE
Use right organization id for all requests

### ISSUE THREAD

**Issue by DasProffi** [helpwave/web#793]
### Describe the chore

Use right organization id for all requests, currently we are defaulting to a specific id instead of using the one of the current organization

**Comment by MaxSchaefer** [comment]
@DasProffi @JannikWibker this is especially for staging relevant right now.

1. Goto https://staging-tasks.helpwave.de/organizations
2. Click on an organisation and then on a ward
3. Nothing loads due to the wrong organisation ID

**Comment by JannikWibker** [comment]
This exact issue seems to be fixed in my clean up PR (#826). Not sure if this happens anywhere else though

**Comment by MaxSchaefer** [comment]
@JannikWibker right. The rooms are now loading but the patient list and assignees on these tasks are still loading https://pr-826-helpwave-web-tasks.fly.dev/ward/8d11df07-aa96-45a0-b1a5-67fb4563a6eb.

**Comment by MaxSchaefer** [comment]
@JannikWibker this issue was not closed with #826 and is one of two urgent issues.

The recently used wards on the dashboard are working fine due to the fact that these wards got created within the default organization. You can access the wards, the patients and so on.

If you click into a ward on the organization list https://staging-tasks.helpwave.de/organizations, the wards inside these organizations are failing entirely due to the invalid organization id in the gRPC metdata header. The header contains the default organization id, this is wrong because the wards are not part of the default organization. The header must contain the organization id of the selected organization. This issue takes place during create and read requests.
